#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#include <stdbool.h>

#ifndef NRF_LOG_ENABLED
#define NRF_LOG_ENABLED 0
#endif
#ifndef NRF_LOG_DEFAULT_LEVEL
#define NRF_LOG_DEFAULT_LEVEL 0
#endif
#ifndef NRF_LOG_DEFERRED
#define NRF_LOG_DEFERRED 0
#endif
#ifndef NRF_FPRINTF_ENABLED
#define NRF_FPRINTF_ENABLED 0
#endif
#ifndef NRF_STRERROR_ENABLED
#define NRF_STRERROR_ENABLED 0
#endif

#ifndef PERIPHERAL_RESOURCE_SHARING_ENABLED
#define PERIPHERAL_RESOURCE_SHARING_ENABLED 0
#endif
#ifndef NRFX_POWER_ENABLED
#define NRFX_POWER_ENABLED 0
#endif

/* UART0: legacy nrf_drv_uart/app_uart over SDK17 nrfx_uart. */
#ifndef UART_ENABLED
#define UART_ENABLED 1
#endif
#ifndef UART0_ENABLED
#define UART0_ENABLED 1
#endif
#ifndef UART1_ENABLED
#define UART1_ENABLED 0
#endif
#ifndef UART_EASY_DMA_SUPPORT
#define UART_EASY_DMA_SUPPORT 0
#endif
#ifndef UART_LEGACY_SUPPORT
#define UART_LEGACY_SUPPORT 1
#endif
#ifndef UART_DEFAULT_CONFIG_HWFC
#define UART_DEFAULT_CONFIG_HWFC NRF_UART_HWFC_DISABLED
#endif
#ifndef UART_DEFAULT_CONFIG_PARITY
#define UART_DEFAULT_CONFIG_PARITY NRF_UART_PARITY_EXCLUDED
#endif
#ifndef UART_DEFAULT_CONFIG_BAUDRATE
#define UART_DEFAULT_CONFIG_BAUDRATE NRF_UART_BAUDRATE_115200
#endif
#ifndef UART_DEFAULT_CONFIG_IRQ_PRIORITY
#define UART_DEFAULT_CONFIG_IRQ_PRIORITY 7
#endif
#ifndef NRFX_UART_ENABLED
#define NRFX_UART_ENABLED 1
#endif
#ifndef NRFX_UART0_ENABLED
#define NRFX_UART0_ENABLED 1
#endif
#ifndef NRFX_UARTE_ENABLED
#define NRFX_UARTE_ENABLED 1
#endif
#ifndef NRFX_UARTE0_ENABLED
#define NRFX_UARTE0_ENABLED 1
#endif
#ifndef NRFX_UARTE1_ENABLED
#define NRFX_UARTE1_ENABLED 0
#endif
#ifndef UART0_CONFIG_HWFC
#define UART0_CONFIG_HWFC NRF_UART_HWFC_DISABLED
#endif
#ifndef UART0_CONFIG_PARITY
#define UART0_CONFIG_PARITY NRF_UART_PARITY_EXCLUDED
#endif
#ifndef UART0_CONFIG_BAUDRATE
#define UART0_CONFIG_BAUDRATE NRF_UART_BAUDRATE_115200
#endif
#ifndef UART0_CONFIG_IRQ_PRIORITY
#define UART0_CONFIG_IRQ_PRIORITY 7
#endif
#ifndef NRFX_UART_DEFAULT_CONFIG_HWFC
#define NRFX_UART_DEFAULT_CONFIG_HWFC NRF_UART_HWFC_DISABLED
#endif
#ifndef NRFX_UART_DEFAULT_CONFIG_PARITY
#define NRFX_UART_DEFAULT_CONFIG_PARITY NRF_UART_PARITY_EXCLUDED
#endif
#ifndef NRFX_UART_DEFAULT_CONFIG_BAUDRATE
#define NRFX_UART_DEFAULT_CONFIG_BAUDRATE NRF_UART_BAUDRATE_115200
#endif
#ifndef NRFX_UART_DEFAULT_CONFIG_IRQ_PRIORITY
#define NRFX_UART_DEFAULT_CONFIG_IRQ_PRIORITY 7
#endif
#ifndef NRFX_UART_CONFIG_LOG_ENABLED
#define NRFX_UART_CONFIG_LOG_ENABLED 0
#endif
#ifndef APP_FIFO_ENABLED
#define APP_FIFO_ENABLED 1
#endif
#ifndef APP_UART_ENABLED
#define APP_UART_ENABLED 1
#endif
#ifndef APP_UART_DRIVER_INSTANCE
#define APP_UART_DRIVER_INSTANCE 0
#endif
#ifndef NRF_DRV_UART_ENABLED
#define NRF_DRV_UART_ENABLED 1
#endif
#ifndef NRF_DRV_UART_CONFIG_USE_EASY_DMA
#define NRF_DRV_UART_CONFIG_USE_EASY_DMA 1
#endif
#ifndef NRF_DRV_UART_PERIPHERAL_ID
#define NRF_DRV_UART_PERIPHERAL_ID 0
#endif
#ifndef NRF_DRV_UART_DEFAULT_CONFIG_HWFC
#define NRF_DRV_UART_DEFAULT_CONFIG_HWFC NRF_UART_HWFC_DISABLED
#endif
#ifndef NRF_DRV_UART_DEFAULT_CONFIG_PARITY
#define NRF_DRV_UART_DEFAULT_CONFIG_PARITY NRF_UART_PARITY_EXCLUDED
#endif
#ifndef NRF_DRV_UART_DEFAULT_CONFIG_BAUDRATE
#define NRF_DRV_UART_DEFAULT_CONFIG_BAUDRATE NRF_UART_BAUDRATE_115200
#endif
#ifndef NRF_DRV_UART_DEFAULT_CONFIG_IRQ_PRIORITY
#define NRF_DRV_UART_DEFAULT_CONFIG_IRQ_PRIORITY 7
#endif
#ifndef NRF_DRV_UART_CONFIG_LOG_ENABLED
#define NRF_DRV_UART_CONFIG_LOG_ENABLED 0
#endif
#ifndef NRFX_UARTE_DEFAULT_CONFIG_HWFC
#define NRFX_UARTE_DEFAULT_CONFIG_HWFC NRF_UARTE_HWFC_DISABLED
#endif
#ifndef NRFX_UARTE_DEFAULT_CONFIG_PARITY
#define NRFX_UARTE_DEFAULT_CONFIG_PARITY NRF_UARTE_PARITY_EXCLUDED
#endif
#ifndef NRFX_UARTE_DEFAULT_CONFIG_BAUDRATE
#define NRFX_UARTE_DEFAULT_CONFIG_BAUDRATE NRF_UARTE_BAUDRATE_115200
#endif
#ifndef NRFX_UARTE_DEFAULT_CONFIG_IRQ_PRIORITY
#define NRFX_UARTE_DEFAULT_CONFIG_IRQ_PRIORITY 7
#endif
#ifndef NRFX_UARTE_CONFIG_LOG_ENABLED
#define NRFX_UARTE_CONFIG_LOG_ENABLED 0
#endif

#endif /* SDK_CONFIG_H */
